export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const ADD_USERS_REQUEST = "ADD_USERS_REQUEST";
export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS";
export const ADD_USERS_FAILURE = "ADD_USERS_FAILURE";

export const GET_USER_PERMISSION_DROPDOWN_DATA_REQUEST = "GET_USER_PERMISSION_DROPDOWN_DATA_REQUEST";
export const GET_USER_PERMISSION_DROPDOWN_DATA_SUCCESS = "GET_USER_PERMISSION_DROPDOWN_DATA_SUCCESS";
export const GET_USER_PERMISSION_DROPDOWN_DATA_FAILURE = "GET_USER_PERMISSION_DROPDOWN_DATA_FAILURE";
