export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAILURE = "GET_USERS_FAILURE";

export const ADD_USERS_REQUEST = "ADD_USERS_REQUEST";
export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS";
export const ADD_USERS_FAILURE = "ADD_USERS_FAILURE";

export const GET_USERS_BYID_REQUEST = "GETUSERS_BYID_REQUEST";
export const GET_USERS_BYID_SUCCESS = "GETUSERS_BYID_SUCCESS";
export const GET_USERS_BYID_FAILURE = "GETUSERS_BYID_FAILURE";

export const EDIT_USERS_BYID_REQUEST = "EDIT_USERS_BYID_REQUEST";
export const EDIT_USERS_BYID_SUCCESS = "EDIT_USERS_BYID_SUCCESS";
export const EDIT_USERS_BYID_FAILURE = "EDIT_USERS_BYID_FAILURE";

export const DELETE_USERS_BYID_REQUEST = "DELETE_ USERS_BYID_REQUEST";
export const DELETE_USERS_BYID_SUCCESS = "DELETE_ USERS_BYID_SUCCESS";
export const DELETE_USERS_BYID_FAILURE = "DELETE_ USERS_BYID_FAILURE";

export const GET_EXISTING_USERS_REQUEST = "GET_EXISTING_USERS_REQUEST";
export const GET_EXISTING_USERS_SUCCESS = "GET_EXISTING_USERS_SUCCESS";
export const GET_EXISTING_USERS_FAILURE = "GET_EXISTING_USERS_FAILURE";

export const GET_USER_PERMISSION_DROPDOWN_DATA_REQUEST = "GET_USER_PERMISSION_DROPDOWN_DATA_REQUEST";
export const GET_USER_PERMISSION_DROPDOWN_DATA_SUCCESS = "GET_USER_PERMISSION_DROPDOWN_DATA_SUCCESS";
export const GET_USER_PERMISSION_DROPDOWN_DATA_FAILURE = "GET_USER_PERMISSION_DROPDOWN_DATA_FAILURE";
